# Pre-built transactions batches.

# Interactive batch execution.
interactive = true

# Genesis block contains executed by built-in (offchain) bootstrap contract.

[[batch.0]]
desc = 'Register vote contract'
file = 'register-vote-0.1.2.bin'
