# Pre-built transactions batches.

# Interactive batch execution.
interactive = true

# Register contracts
[[batch.0]]
desc = 'Register asset contract'
file = 'register-asset-0.1.2.bin'

[[batch.1]]
desc = 'init asset'
file = 'asset-init.bin'

[[batch.1]]
desc = 'register escrow contract'
file = 'register-escrow-0.2.3.bin'
